### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by ghost** [leeprky/Quarrel#1]
epic theme

**Comment by ghost** [comment]
also, spotify control things dont work with this theme 💢

**Comment by ar06x** [comment]
> also, spotify control things dont work with this theme 💢

Very

**Comment by leeprky** [comment]
![spotify](https://user-images.githubusercontent.com/71296232/118467847-15483680-b6fc-11eb-94bc-8bf12309b68e.png)

??

**Comment by ghost** [comment]
for me i cant see the skip forward and skip backwards button

**Comment by Squensay** [comment]
Same here the spotify interface is somewhat broken 
![image](https://user-images.githubusercontent.com/55328134/118551845-756fc480-b75e-11eb-92ef-641abcb210b5.png)

**Comment by Squensay** [comment]
For anyone who want to make the spotify plugin work again i made a fix https://github.com/Squensay/Quarrel-spotify-fix

**Comment by leeprky** [comment]
Its Hard To Fix This Without Breaking The Bottom Bar

**Comment by ghost** [comment]
I tried to fix it, you can check if you want https://github.com/Squensay/Quarrel-spotify-fix

**Comment by leeprky** [comment]
Oh Cool i’ll test it later

**Comment by leeprky** [comment]
Merged
