### ISSUE TITLE
It says "Quarrel is outdated or broken"

### ISSUE THREAD

**Issue by ghost** [leeprky/Quarrel#10]
This looks similar to a previously closed issue. (#5)

![image](https://user-images.githubusercontent.com/67515294/142939058-7e420109-4ca5-41c6-b761-7f566cbcbf6a.png)

**Comment by NeonixRIT** [comment]
It shows this because they updated the theme... as suggested, redownload the new version. If you're using BetterDiscord, here is the new version: https://raw.githubusercontent.com/leeprky/Quarrel/main/support/betterdiscord/quarrel.theme.css

**Comment by 19216800** [comment]
> It shows this because they updated the theme... as suggested, redownload the new version. If you're using BetterDiscord, here is the new version: https://raw.githubusercontent.com/leeprky/Quarrel/main/support/betterdiscord/quarrel.theme.css

Yeaaahhhhh...No still shows oudated even with v1.6 nice try Quarrel...
